version: '3'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis:
    image: 'redis:latest'      
  client:
    build: 
     dockerfile: Dockerfile
     context: ./client
    volumes:
     - /usr/src/app/node_modules
     - ./client:/usr/src/app
  api:
    depends_on:
      - redis
      - postgres
    build:
      dockerfile: Dockerfile
      context: ./server
    volumes:
     - /usr/src/app/node_modules
     - ./server:/usr/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'                                                                      
  worker:
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app                                                                                                                                                        
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379                 